[package]
name = "rocket_hello"
version = "0.1.0"
authors = ["myyrakle <sssang97@naver.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates"]
